// TypeScript Types 
var myString;
var myNumber;
var myBoolean;
var myAny;
var myArrString;
var myArrNumber;
var myArrBoolean;
var myTuple;
var myVoid = undefined;
var myNull = null;
var myUndefined = null;
myString = 'Hello TypeScript';
myNumber = 22;
myBoolean = false;
myAny = 4;
myArrString = ['Hello', 'World'];
myArrNumber = [1, 2, 3];
myArrBoolean = [true, false];
myTuple = ['Hello ', 8]; // Array with fixed number of elements , first element has to be string as declare above and vice versa
console.log('String : ', myString);
console.log('Number :', myNumber);
console.log('Boolean : ', myBoolean);
console.log('Any : ', myAny);
console.log('String Array : ', myArrString);
console.log('Number Array  : ', myArrNumber);
console.log('Boolean Array : ', myArrBoolean);
console.log('Tuple Array : ', myTuple);
console.log('Void : ', myVoid);
console.log('Null : ', myNull);
console.log('Undefined : ', myUndefined);
